const SET_PICKED_COMMIT = 'SET_PICKED_COMMIT'
const SET_COMMIT_SOURCE = 'SET_COMMIT_SOURCE'
const FETCH_COMMIT = 'FETCH_COMMIT'
const COMMIT_FETCH_SUCCEEDED = 'COMMIT_FETCH_SUCCEEDED'
const COMMIT_FETCH_FAIL = 'COMMIT_FETCH_FAIL'
const LOADING = 'LOADING'

export default {
	SET_PICKED_COMMIT,
	SET_COMMIT_SOURCE,
	FETCH_COMMIT,
	COMMIT_FETCH_SUCCEEDED,
	COMMIT_FETCH_FAIL,
	LOADING,
}